AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreditRiskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: awsLambdaProj.app.handler
      Runtime: python3.12
      CodeUri: ./awsLambdaProj/
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        CreditRiskApi:
          Type: Api
          Properties:
            Path: /credit
            Method: post